=== lbds137/cos984-senior-thesis-2014/misc/settlersBoardSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com" elementFormDefault="qualified">

<xs:element name="board" maxOccurs="1" minOccurs="1">
    <xs:complexType>
        <xs:sequence>
            <!-- hexGraph: for each hex (node), record adjacent hexes (edges between this and other hex) -->
            <xs:element name="hexGraph" maxOccurs="1" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="hex" maxOccurs="19" minOccurs="19">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="id" type="xs:integer"/>  
                                    <xs:element name="adjacentId" type="xs:integer" maxOccurs="6" minOccurs="2"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <!-- intersectionGraph: for each intersection (node), record adjacent intersections (edge between this and other intersection) -->
            <xs:element name="intersectionGraph" maxOccurs="1" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="intersection" maxOccurs="54" minOccurs="54">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="id" type="xs:integer"/>  
                                    <xs:element name="adjacentId" type="xs:integer" maxOccurs="3" minOccurs="2"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <!-- hexToIntersectionMapGraph: for each hex (node), record adjacent intersections (edge between this hex and other intersection) -->
            <xs:element name="hexToIntersectionMapGraph" maxOccurs="1" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="hexToIntersectionMap" maxOccurs="6" minOccurs="6">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="id" type="xs:integer"/>  
                                    <xs:element name="adjacentId" type="xs:integer" maxOccurs="6" minOccurs="6"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== lbds137/cos984-senior-thesis-2014/Spring/settlersBoard.xml
<?xml version="1.0"?>

<board
xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com settlersBoardSchema.xsd">
    <hexGraph>
        <hex>
            <id>0</id>
            <adjacentId>1</adjacentId>
            <adjacentId>3</adjacentId>
            <adjacentId>4</adjacentId>
        </hex>
        <hex>
            <id>1</id>
            <adjacentId>0</adjacentId>
            <adjacentId>2</adjacentId>
            <adjacentId>4</adjacentId>
            <adjacentId>5</adjacentId>
        </hex>
        <hex>
            <id>2</id>
            <adjacentId>1</adjacentId>
            <adjacentId>5</adjacentId>
            <adjacentId>6</adjacentId>
        </hex>
        <hex>
            <id>3</id>
            <adjacentId>0</adjacentId>
            <adjacentId>4</adjacentId>
            <adjacentId>7</adjacentId>
            <adjacentId>8</adjacentId>
        </hex>
        <hex>
            <id>4</id>
            <adjacentId>0</adjacentId>
            <adjacentId>1</adjacentId>
            <adjacentId>3</adjacentId>
            <adjacentId>5</adjacentId>
            <adjacentId>8</adjacentId>
            <adjacentId>9</adjacentId>
        </hex>
        <hex>
            <id>5</id>
            <adjacentId>1</adjacentId>
            <adjacentId>2</adjacentId>
            <adjacentId>4</adjacentId>
            <adjacentId>6</adjacentId>
            <adjacentId>9</adjacentId>
            <adjacentId>10</adjacentId>
        </hex>
        <hex>
            <id>6</id>
            <adjacentId>2</adjacentId>
            <adjacentId>5</adjacentId>
            <adjacentId>10</adjacentId>
            <adjacentId>11</adjacentId>
        </hex>
        <hex>
            <id>7</id>
            <adjacentId>3</adjacentId>
            <adjacentId>8</adjacentId>
            <adjacentId>12</adjacentId>
        </hex>
        <hex>
            <id>8</id>
            <adjacentId>3</adjacentId>
            <adjacentId>4</adjacentId>
            <adjacentId>7</adjacentId>
            <adjacentId>9</adjacentId>
            <adjacentId>12</adjacentId>
            <adjacentId>13</adjacentId>
        </hex>
        <hex>
            <id>9</id>
            <adjacentId>4</adjacentId>
            <adjacentId>5</adjacentId>
            <adjacentId>8</adjacentId>
            <adjacentId>10</adjacentId>
            <adjacentId>13</adjacentId>
            <adjacentId>14</adjacentId>
        </hex>
        <hex>
            <id>10</id>
            <adjacentId>5</adjacentId>
            <adjacentId>6</adjacentId>
            <adjacentId>9</adjacentId>
            <adjacentId>11</adjacentId>
            <adjacentId>14</adjacentId>
            <adjacentId>15</adjacentId>
        </hex>
        <hex>
            <id>11</id>
            <adjacentId>6</adjacentId>
            <adjacentId>10</adjacentId>
            <adjacentId>15</adjacentId>
        </hex>
        <hex>
            <id>12</id>
            <adjacentId>7</adjacentId>
            <adjacentId>8</adjacentId>
            <adjacentId>13</adjacentId>
            <adjacentId>16</adjacentId>
        </hex>
        <hex>
            <id>13</id>
            <adjacentId>8</adjacentId>
            <adjacentId>9</adjacentId>
            <adjacentId>12</adjacentId>
            <adjacentId>14</adjacentId>
            <adjacentId>16</adjacentId>
            <adjacentId>17</adjacentId>
        </hex>
        <hex>
            <id>14</id>
            <adjacentId>9</adjacentId>
            <adjacentId>10</adjacentId>
            <adjacentId>13</adjacentId>
            <adjacentId>15</adjacentId>
            <adjacentId>17</adjacentId>
            <adjacentId>18</adjacentId>
        </hex>
        <hex>
            <id>15</id>
            <adjacentId>10</adjacentId>
            <adjacentId>11</adjacentId>
            <adjacentId>14</adjacentId>
            <adjacentId>18</adjacentId>
        </hex>
        <hex>
            <id>16</id>
            <adjacentId>12</adjacentId>
            <adjacentId>13</adjacentId>
            <adjacentId>17</adjacentId>
        </hex>
        <hex>
            <id>17</id>
            <adjacentId>13</adjacentId>
            <adjacentId>14</adjacentId>
            <adjacentId>16</adjacentId>
            <adjacentId>18</adjacentId>
        </hex>
        <hex>
            <id>18</id>
            <adjacentId>14</adjacentId>
            <adjacentId>15</adjacentId>
            <adjacentId>17</adjacentId>
        </hex>
    </hexGraph>
    
    <intersectionGraph>
        <intersection>
            <id>0</id>
            <adjacentId>1</adjacentId>
            <adjacentId>8</adjacentId>
        </intersection>
        <!-- todo -->
    </intersectionGraph>
        
    <hexToIntersectionMapGraph>
        <!-- todo -->
    </hexToIntersectionMapGraph>
</board>
